services:
  - type: web
    name: Financial-Document-Q-A-RAG-Powered-SEC-Filing-Assistant
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /

  - type: web
    name: financial-rag-ui
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install streamlit requests python-dotenv
    startCommand: streamlit run frontend/ui.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        value: https://financial-rag-api.onrender.com
